src/Entity/Questions.php
<?php

namespace App\Entity;

use App\Repository\QuestionsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=QuestionsRepository::class)
 */
class Questions
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="questions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $question_title;

    /**
     * @ORM\Column(type="text")
     */
    private $question;

    /**
     * @ORM\OneToMany(targetEntity=Answers::class, mappedBy="question")
     */
    private $answers;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $votes;

    /**
     * @ORM\Column(type="string", length=255, options={"default": 0})
     */
    private $topic;

    public function __construct()
    {
        $this->answers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getQuestionTitle(): ?string
    {
        return $this->question_title;
    }

    public function setQuestionTitle(string $question_title): self
    {
        $this->question_title = $question_title;

        return $this;
    }

    public function getQuestion(): ?string
    {
        return $this->question;
    }

    public function setQuestion(string $question): self
    {
        $this->question = $question;

        return $this;
    }

    /**
     * @return Collection|Answers[]
     */
    public function getAnswers(): Collection
    {
        return $this->answers;
    }

    public function addAnswer(Answers $answer): self
    {
        if (!$this->answers->contains($answer)) {
            $this->answers[] = $answer;
            $answer->setQuestion($this);
        }

        return $this;
    }

    public function removeAnswer(Answers $answer): self
    {
        if ($this->answers->removeElement($answer)) {
            // set the owning side to null (unless already changed)
            if ($answer->getQuestion() === $this) {
                $answer->setQuestion(null);
            }
        }

        return $this;
    }

    public function getVotes(): ?int
    {
        return $this->votes;
    }

    public function setVotes(?int $votes): self
    {
        $this->votes = $votes;

        return $this;
    }

    public function getTopic(): ?string
    {
        return $this->topic;
    }

    public function setTopic(string $topic): self
    {
        $this->topic = $topic;

        return $this;
    }
}

src/Form/QuestionsType.php
<?php

namespace App\Form;

use App\Entity\Questions;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;


class QuestionsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('question_title')
            ->add('question')
            ->add('topic', ChoiceType::class, [
                'choices'  => [
                    'Physics' => 0,
                    'Chemistry' => 1,
                    'Biology' => 2,
                ],
            ])
            // ->add('user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Questions::class,
        ]);
    }
}

src/Controller/QuestionsController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Questions;

use App\Form\QuestionsType;
use App\Repository\QuestionsRepository;
use App\Repository\AnswersRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/questions')]
class QuestionsController extends AbstractController
{
    #[Route('/', name: 'questions_index', methods: ['GET'])]
    public function index(QuestionsRepository $questionsRepository): Response
    {
        return $this->render('questions/index.html.twig', [
            'questions' => $questionsRepository->findAll(),
        ]);
    }

    #[Route('/ask-question', name: 'questions_new', methods: ['GET','POST'])]
    public function new(Request $request): Response
    {
        $user = $this->getUser();

        $question = new Questions();

        // //set foreign key
        $question->setUser($user);

        $form = $this->createForm(QuestionsType::class, $question);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($question);
            $entityManager->flush();

            return $this->redirectToRoute('questions_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('questions/new.html.twig', [
            'question' => $question,
            'form' => $form,
        ]);
    }

    #[Route('/individual/{id}', name: 'individual_question', methods: ['GET','POST'])]
    public function selected(Request $request, QuestionsRepository $questionsRepository, AnswersRepository $answersRepository): Response
    {

        $id = $request->get('id');

        // echo $id;
        // die;

        // ajax voter

        if($request->isXmlHttpRequest()) { //if we are receiving a HTTP request
            
            //get the POST data - id
            
            
            $votes = 0; //default
            $questionId = $_POST['id'];
            $voteType = $_POST['voteType'];
            
            $entityManager = $this->getDoctrine()->getManager();
            //get the questions that was liked
            $questionsVote = $entityManager->getRepository(Answers::class)->find($questionId);
            //update the votes to the questionss current count - using the getter
            $votes = $questionsVote->getVotes();
            //update our entity using the setter
            
            if($voteType == 1 ){
                $questionsVote->setVotes($votes + 1);

                $entityManager->flush();
                return $votes + 1;

            }
            
            if($voteType == 0){
                $questionsVote->setVotes($votes - 1);
                
                $entityManager->flush();
                return $votes - 1;


            }

            //TODO: - Add questions id and user id to votes table


        }

        return $this->render('individual_question.html.twig', [
            'questions' => $questionsRepository->find($id),
            'answers' => $answersRepository->findByQuestion($id),
        ]);
    }

    #[Route('/{id}', name: 'questions_show', methods: ['GET'])]
    public function show(Questions $question): Response
    {
        return $this->render('questions/show.html.twig', [
            'question' => $question,
        ]);
    }

    #[Route('/{id}/edit', name: 'questions_edit', methods: ['GET','POST'])]
    public function edit(Request $request, Questions $question): Response
    {
        $form = $this->createForm(QuestionsType::class, $question);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('questions_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('questions/edit.html.twig', [
            'question' => $question,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'questions_delete', methods: ['POST'])]
    public function delete(Request $request, Questions $question): Response
    {
        if ($this->isCsrfTokenValid('delete'.$question->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($question);
            $entityManager->flush();
        }

        return $this->redirectToRoute('questions_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/questions/_delete_form.html.twig
<form method="post" action="{{ path('questions_delete', {'id': question.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ question.id) }}">
    <button class="btn">Delete</button>
</form>

templates/questions/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn register_btn" style="margin: 10px 0 -100px 290px !important">{{ button_label|default('Ask') }}</button>
    
{{ form_end(form) }}

templates/questions/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Questions{% endblock %}

{% block body %}
    <h1>Edit Questions</h1>

    {{ include('questions/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('questions_index') }}">back to list</a>

    {{ include('questions/_delete_form.html.twig') }}
{% endblock %}

templates/questions/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Questions index{% endblock %}

{% block body %}
    <h1>Questions index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Question_title</th>
                <th>Question</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for question in questions %}
            <tr>
                <td>{{ question.id }}</td>
                <td>{{ question.questionTitle }}</td>
                <td>{{ question.question }}</td>
                <td>
                    <a href="{{ path('questions_show', {'id': question.id}) }}">show</a>
                    <a href="{{ path('questions_edit', {'id': question.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('questions_new') }}">Create new</a>
{% endblock %}

templates/questions/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Questions{% endblock %}

{% block body %}
    <h1 class="h3 header col-12 text-center" style="margin: 30px 0 30px 0">Ask Question</h1>

    {{ include('questions/_form.html.twig') }}

    {# <a href="{{ path('questions_index') }}" class="back_btn">
        <i class="fas fa-chevron-left"></i>
        back to list
    </a> #}

    <style>
       :root {
    --primary-font-family:  'Nunito Sans', sans-serif;
 
    /* --gradient: linear-gradient(45deg, #FFDD99, #FF99BB); 
    --colour-one: #FFDD99;
    --colour-two: #FF99BB;
    --colour-three: #4200FF;
 
    --success-alert: #80FFBF;
    --error-alert: #FF6666; */
 
   }

body, h1, h2, h3, h4, h5, h6, p, .row{
    margin: 0;
    padding: 0;
}

.back_btn{
    font-family: var(--primary-font-family);
    font-size: 32px;
    font-weight: 700;
    padding-top: 20px;
    width: 385px;
    height: 84px;
    border: 7px solid #000000;
    border-radius: 16px;
    padding: 15px;
    margin: 10px 0 -210px 115px;
    background-color: #000;
    text-decoration: none;
    color: #fff;
}

select{
    width: 205px;
    height: 63.9px;
    font-size: 20px;
    margin-left: 120px;
    font-family: var(--primary-font-family);
    padding: 0 20px;
    border-radius: 8px;
    border: 4px solid #000000; 
    background-color: #fff;
    color: #000;
}

option{
    font-weight: 700;
}

#user, #questions{
    margin: 0 650px;
}

#questions input, #questions textarea{
    width: 110%;;
    margin: 15px 0 !important;
    flex: 0 0 auto;
    width: 100%;
}

textarea{
    height: 300px !important;
}

.sign_in_anchor, .sign_in_anchor:hover{
    color: #fff;
    text-decoration: none;
}

.register_anchor, .register_anchor:hover{
    color: #000;
    text-decoration: none;
}

.sign_in_header{
    margin: 164px 0 72px 0;
    
}

.profile_picture{
    width: 200px;
    height: 200px;
    background-color: #FFD966;
    border: 7px solid #000;
    border-radius: 132px;
    margin: 72px auto 64px auto;
}

.form_input{
    /* margin-top: 100px; */
}

input, textarea{
    height: 84px;
    width: 50%;
    min-width: 385px;
    border: 7px solid #000000;
    border-radius: 16px;
    margin: 40px 0 0 0 !important;
    padding-left: 16px !important;
    font-family:var(--primary-font-family);
    font-size: 24px;
    font-weight: 700;
    color: #000000;
}

input:focus, textarea:focus{
    background: #FFD966;
    outline: none;
}

input::placeholder, textarea::placeholder{
    font-family:var(--primary-font-family);
    font-size: 24px;
    font-weight: 700;
    color: #000000;

}

label{
    font-family: var(--primary-font-family);
    font-size:20px;
    font-weight: 700;
    color: #000000;
    margin: 0 0 -50px 0;
}

.small_input input:nth-child(1){
    margin-right: 48px !important;
}

.small_input input{
    min-width: 340px;
}

.btns{
    font-family:var(--primary-font-family);
    font-size: 32px;
    font-weight: 700;
    padding-top: 20px;
}

.button{
    height: 84px;
    border: 7px solid #000000;
    border-radius: 16px;
    padding-top: 10px;
    margin: 0 0 24px 0;
}

.register_btn{
    font-family: var(--primary-font-family);
    font-size: 32px;
    font-weight: 700;
    color: #000000;
    padding-top: 20px;
    width: 385px;
    height: 84px;
    border: 7px solid #000000;
    border-radius: 16px;
    padding-top: 10px;
    margin: 10px 0 -470px -800px;
    background-color: #FFD966;
    color: #000;
    transform: translateX(107%);
}

.sign_in_btn{
    font-family: var(--primary-font-family);
    font-size: 32px;
    font-weight: 700;
    padding-top: 20px;
    width: 385px;
    height: 84px;
    border: 7px solid #000000;
    border-radius: 16px;
    padding-top: 10px;
    margin: 10px 0 -210px -200px;
    background-color: #000;
    color: #fff;
}

.delete_btn{
    font-family: var(--primary-font-family);
    font-size: 32px;
    font-weight: 700;
    padding-top: 20px;
    width: 385px;
    height: 84px;
    border: 7px solid #000000;
    border-radius: 16px;
    padding-top: 10px;
    margin: 10px 0 -210px 700px;
    background-color: #ff6666;
    color: #000;
}

.back_btn{
    font-family: var(--primary-font-family);
    font-size: 32px;
    font-weight: 700;
    padding-top: 20px;
    width: 385px;
    height: 84px;
    border: 7px solid #000000;
    border-radius: 16px;
    padding: 15px;
    margin: 10px 0 -210px 115px;
    background-color: #000;
    text-decoration: none;
    color: #fff;
}

.sign_in_btn:hover{
    border: 7px solid #000;
    background-color: #fff;
    color: #000;
}

@media (min-width: 500px) and (max-width: 767.98px) {

    .sign_in_btn{
        margin-left: 55px;
    }

    .register_btn{
        margin-left: 55px;
    }

    .profile_picture {
      width: 200px;
      height: 200px;
      margin: 100px auto 23px auto;
    }

    input{
        margin-top: 30px !important;
    }

    .username{
        min-width: 340px;
        margin: 30px 0 0 -4px !important;
    }
    
    .password{
        min-width: 340px;
        margin: 30px 0 0 -4px !important;
        
    }
    
    .email{
        min-width: 340px;
        margin: 30px 0 0 -194px !important;
    }
    
    .number{
        min-width: 340px;
        margin: 30px 0 0 49px !important;
        
    }
    .button{
        margin-top: 20px;
    }
    
}
    .form_widget{
        transform: translateX(10%);
    }
    
    .form_widget input{
        height: 64px !important;
        border: 4px solid #000000;
        border-radius: 16px;
        margin: 40px 0 0 -105px !important;
        padding-left: 16px !important;
        font-family:var(--primary-font-family);
        font-size: 24px;
        font-weight: 700;
        color: #000000;
    }

    

  @media (min-width: 992px){

    input, textarea{
        height: 64px;
        border: 4px solid #000000;
        border-radius: 16px;
        margin: 40px 0 0 0 !important;
        padding-left: 16px !important;
        font-family:var(--primary-font-family);
        font-size: 24px;
        font-weight: 700;
        color: #000000;
    }

    .profile_picture{
        width: 164px;
        height: 164px;
        background-color: #FFD966;
        border: 7px solid #000;
        border-radius: 132px;
        margin: 80px auto 50px auto;
    }

    .profile_input{
        height: 64px;
        border: 4px solid #000000;
        border-radius: 16px;
        margin: 40px 10px 0 0 !important;
        padding-left: 16px !important;
        font-family:var(--primary-font-family);
        font-size: 24px;
        font-weight: 700;
        color: #000000;
    }
    
    .form_input{
        padding: 0 30%;
    }

    .small_input input:nth-child(1){
        margin-right: 42px !important;
        margin-left: 334px !important;
    }

    .big_input input:nth-child(2){
        margin-right: 42px !important;
        /* margin-left: 334px !important; */
        min-width: 305px;
    }

    .big_input input:nth-child(3){
        min-width: 305px;
    }

    .small_input input{
        min-width: 305px;
    }

    .button{
        height: 84px;
        border: 7px solid #000000;
        border-radius: 16px;
        padding-top: 10px;
        margin: 40px -16% 24px -16%;
    }

    .update_btn{
        background-color: #FFD966;
        color: #000;
    }

    .sign_in_header{
        margin: 140px 0 72px 0 !important;
    }

}

.header{
    font-size: 60px;
    font-family: var(--primary-font-family);
    font-weight: 700;
    margin: 250px 0 0 0;
} 
    </style>

{% endblock %}

templates/questions/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Questions{% endblock %}

{% block body %}
    <h1>Questions</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ question.id }}</td>
            </tr>
            <tr>
                <th>Question_title</th>
                <td>{{ question.questionTitle }}</td>
            </tr>
            <tr>
                <th>Question</th>
                <td>{{ question.question }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('questions_index') }}">back to list</a>

    <a href="{{ path('questions_edit', {'id': question.id}) }}">edit</a>

    {{ include('questions/_delete_form.html.twig') }}
{% endblock %}